### ISSUE TITLE
https://www.theguardian.com/uk/rss

### ISSUE THREAD

**Issue by afandian** [CrossRef/event-data-enquiries#34]
are you tracking this newsfeed?

**Comment by crossref-support** [comment]
Hi! This is the Event Data Support bot! That looks like an RSS feed. 

I checked in our Newsfeed list and I can confirm that we do follow that RSS feed. You can find it in the current Newsfeed Artifact, found here:

 - https://artifact.eventdata.crossref.org/a/newsfeed-list/versions/1515417992862

Did I answer your support query? If so, feel free to close this ticket. If not, reply and we'll get back to you.

**Comment by afandian** [comment]
Yeah cheers my mistake.
